enum Step {
  SELECT_TEMPLATE = 'SELECT_TEMPLATE',
  UPLOAD_PROFILE_IMAGE = 'UPLOAD_PROFILE_IMAGE',
  PROFILE_CROPPING = 'PROFILE_CROPPING',
  MAPPING_FINAL_IMAGE = 'MAPPING_FINAL_IMAGE',
}

export default Step;
